### ISSUE TITLE
Space Ship ideas

### ISSUE THREAD

**Issue by BernardSheeran** [VinSlif/Team10#6]
Everyone find a picture of what you think Yuri's space ship should look like. think outside the norm, a black and white fat rocket is boring. Do this ASAP

**Comment by insanity180** [comment]
Model wise I imagined something like this nuclear age space ship. https://maugryph.files.wordpress.com/2015/09/penholder-spaceship.jpg

**Comment by BernardSheeran** [comment]
http://image.noelshack.com/fichiers/2016/17/1461927317-tauship.jpg
http://assets1.ignimgs.com/thumbs/userUploaded/2016/4/7/battlefleetgothicarmadaeldartrailerign-1460041070190_large.jpg
http://playertheory.com/images/Gothic3.jpg
http://img00.deviantart.net/751f/i/2005/077/5/1/saem_hann_vampire_by_ranin.jpg
http://vignette1.wikia.nocookie.net/warhammer40k/images/a/a6/Eldar_Vypers_combat.png/revision/latest?cb=20150308191833
https://i.ytimg.com/vi/QcXgqmHby9E/maxresdefault.jpg

these would be simplified obviously but just getting creative juices flowing

**Comment by VinSlif** [comment]
http://vignette3.wikia.nocookie.net/tokusatsu/images/f/f8/The_Yamato.jpg/revision/latest?cb=20130320020120
http://www.collectiondx.com/files/hasearc1.jpg
http://vignette1.wikia.nocookie.net/destinypedia/images/9/94/Spaceships.png/revision/latest?cb=20140601094011
http://vignette4.wikia.nocookie.net/firefly/images/1/11/Firefly_class_ship.jpg/revision/latest?cb=20090714124528
This is more of a giant collection of ships
http://orig03.deviantart.net/494a/f/2014/171/0/1/size_comparison___science_fiction_spaceships_by_dirkloechel-d6lfgdf.jpg

**Comment by jwk352** [comment]
I loaded up a bunch of references to the Drive in the Concept Art folder.

**Comment by jwk352** [comment]
https://drive.google.com/drive/folders/0BySxjQhI2-ZTX2QyWXF4X3BPVVE
